package com.freud.zk;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.freud.zkadmin.business.zk.bean.ZkInstanceBean;

/**
 * 
 * @author Freud
 *
 */
public interface ZkInstanceBeanMapper {

	public static final String ZK_INSTANCE_COLUMNS = "NAME,IP,PORT,USE,OPERATE_DATE";
	
	@Select("CREATE TABLE ZK_INSTANCE(" +
			"	ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1)," +  
			"	NAME VARCHAR(128) NOT NULL," +
			"	IP VARCHAR(15) NOT NULL," +
			"	PORT INT," +
			"	USE INT," +
			"	OPERATE_DATE TIMESTAMP," +
			"	CONSTRAINT PK_T_ZK_INSTANCE PRIMARY KEY (ID)" +
			")")
	public void createTables();
	
	@Select("SELECT ID,"+ZK_INSTANCE_COLUMNS+" FROM ZK_INSTANCE ORDER BY OPERATE_DATE DESC")
	public List<ZkInstanceBean> getAll();
	
	@Select("SELECT ID,"+ZK_INSTANCE_COLUMNS+" FROM ZK_INSTANCE WHERE ID = #{id}")
	public ZkInstanceBean get(@Param("id")int id);
	
	@Insert("INSERT INTO ZK_INSTANCE ("+ZK_INSTANCE_COLUMNS+") VALUES(#{name},#{ip},#{port},#{use},CURRENT_TIMESTAMP)")
	public void insert(ZkInstanceBean zkInstanceBean);
	
	@Update("UPDATE ZK_INSTANCE SET NAME=#{name},IP=#{ip},USE=#{use},PORT=#{port},OPERATE_DATE=CURRENT_TIMESTAMP WHERE ID=#{id}")
	public void update(ZkInstanceBean zkInstanceBean);
	
	@Delete("DELETE FROM ZK_INSTANCE WHERE ID = #{id}")
	public void delete(@Param("id")int id);
}
